# Generated by Django 6.1.1 on 2026-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('fecha_expiracion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
