# Generated by Django 6.1.1 on 2026-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ecf', models.CharField(choices=[('31', 'Factura de Crédito Fiscal'), ('32', 'Factura de Consumo'), ('34', 'Nota de Crédito'), ('33', 'Nota de Débito')], max_length=2)),
                ('e_ncf', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('firmado', 'Firmado'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_cola', 'En cola de contingencia')], default='generado', max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('monto_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_exento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('xml_content', models.TextField(blank=True)),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.PositiveIntegerField()),
                ('nombre_item', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_item', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc_cedula', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
