# Generated by Django 6.1.1 on 2026-09-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobantes', '0001_initial'),
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='emisores.emisor'),
        ),
        migrations.AddField(
            model_name='itemcomprobante',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comprobantes.comprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='comprobantes.receptor'),
        ),
    ]
