# Generated by Django 6.1.1 on 2026-09-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('proximo_intento', models.DateTimeField()),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cola', to='comprobantes.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='LogTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='comprobantes.comprobante')),
            ],
        ),
    ]
